spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql

bot:
  name: bro_crypto_bot
  token:
  max-chats: 50

api:
  url: https://api.mexc.com/api/v3/ticker/price
  refresh-rate: 10

currency:
  percent: 5