DROP TABLE IF EXISTS currency;

CREATE TABLE currency (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(50) UNIQUE NOT NULL,
  price DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS chats (
    id INT PRIMARY KEY
);
